apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "vm-linux.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: custom
      {{- if and ( or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") ) (.Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- if .Values.server.ports }}  
    {{- range untilStep (int .Values.server.ports.workProccesStartPort) (int .Values.server.ports.workProccesEndPort) 1 }}  
    - protocol: TCP
      name: wp-{{ . }}
      port: {{ (int .) }}
    {{- end }}
    - protocol: TCP
      name: clmen
      port: {{ .Values.server.ports.serveragent }}
    - protocol: TCP
      name: cluster
      port: {{ .Values.server.ports.clusterManagerPort }}
    - name: ras
      port: {{ .Values.server.ports.rasPort }}
    {{- end }}  
  {{- if and (eq .Values.service.type "LoadBalancer") (.Values.service.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  selector:
    {{- include "vm-linux.selectorLabels" . | nindent 4 }}
