apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .Release.Name }}
  creationTimestamp: null
  labels:
    {{- include "vm-linux.labels" . | nindent 4 }}
spec:
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "vm-linux.labels" . | nindent 8 }}
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
    spec:
      domain:
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
        devices:
          disks:
            - name: containerdisk
              cdrom:
                bus: sata
              bootOrder: 2  
            {{- with .Values.disks }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- range .Values.disks }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ $.Release.Name }}-{{ .name }}
        {{- end }}
        - name: containerdisk
          containerDisk:
            image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
